// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v5.26.0--rc1

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class SyntaxResponse {
  static encode(message: SyntaxResponse, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.output);
  }

  static decode(reader: Reader, length: i32): SyntaxResponse {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new SyntaxResponse();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.output = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  output: string;

  constructor(output: string = "") {
    this.output = output;
  }
}

export function encodeSyntaxResponse(message: SyntaxResponse): Uint8Array {
  return Protobuf.encode(message, SyntaxResponse.encode);
}

export function decodeSyntaxResponse(buffer: Uint8Array): SyntaxResponse {
  return Protobuf.decode<SyntaxResponse>(buffer, SyntaxResponse.decode);
}
