// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v5.26.0--rc1

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class SyntaxRequest {
  static encode(message: SyntaxRequest, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.code);

    writer.uint32(18);
    writer.string(message.language);
  }

  static decode(reader: Reader, length: i32): SyntaxRequest {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new SyntaxRequest();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.code = reader.string();
          break;

        case 2:
          message.language = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  code: string;
  language: string;

  constructor(code: string = "", language: string = "") {
    this.code = code;
    this.language = language;
  }
}

export function encodeSyntaxRequest(message: SyntaxRequest): Uint8Array {
  return Protobuf.encode(message, SyntaxRequest.encode);
}

export function decodeSyntaxRequest(buffer: Uint8Array): SyntaxRequest {
  return Protobuf.decode<SyntaxRequest>(buffer, SyntaxRequest.decode);
}
