// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v5.26.0--rc1

import { Writer, Reader, Protobuf } from "as-proto/assembly";

export class VersionRequest {
  static encode(message: VersionRequest, writer: Writer): void {}

  static decode(reader: Reader, length: i32): VersionRequest {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new VersionRequest();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  constructor() {}
}

export function encodeVersionRequest(message: VersionRequest): Uint8Array {
  return Protobuf.encode(message, VersionRequest.encode);
}

export function decodeVersionRequest(buffer: Uint8Array): VersionRequest {
  return Protobuf.decode<VersionRequest>(buffer, VersionRequest.decode);
}
